application:
  service:
    departments:
      host: localhost
      port: 8003
    employees:
      host: localhost
      port: 8002
    locations:
      host: localhost
      port: 8001

logging.level.org.springframework.web: INFO

spring.thymeleaf:
  cache: false
  reactive.max-chunk-size: 8192

