application:
  services:
    departments:
      host: ${DEPARTMENTS_HOST:localhost}
      port: 8002
    employees:
      host: ${EMPLOYEES_HOST:localhost}
      port: 8003
    locations:
      host: ${LOCATIONS_HOST:localhost}
      port: 8001

logging.level.org.springframework.web: INFO

spring.thymeleaf:
  cache: false
  reactive.max-chunk-size: 8192
