application:
  r2dbc:
    host: "localhost"
    database: "db"
    username: "dbuser"
    password: "password"

logging:
  level:
    org.springframework:
      web: INFO
      data.r2dbc: DEBUG

server:
  port: 8003
